language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 9
before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_19950a533095_key
    -iv $encrypted_19950a533095_iv
    -in github_deploy_key.enc
    -out github_deploy_key
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
script:
  # deploy to netlify
  - yarn build
  - git remote -v
  - yarn deploy
branches:
  - master
