language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 9
before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_19950a533095_key
    -iv $encrypted_19950a533095_iv
    -in github_deploy_key.enc
    -out github_deploy_key
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
script:
  - npm run generate:gh-pages
  - cd dist
  - git init
  - git remote add origin git@github.com:developersjp/podcast-freaks.git
  - git checkout -b gh-pages
  - git add .
  - git commit -m 'Builds on travis'
  - git push origin gh-pages --force
  # - ls
  # - touch ~/.ssh/id_rsa
  # - touch ~/.ssh/config
  # - chmod 600 ~/.ssh/id_rsa
  # - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # - git config --global user.email "naokazu.terada@gmail.com"
  # - git config --global user.name "Naokazu Terada"
  # - git checkout -b 'gh-pages'
  # - git commit --allow-empty -m 'Auto build'
  # - git push origin gh-pages --force
branches:
  - master
