language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - stable
script:
  - npm run generate:gh-pages
  - git remote set-url origin git@github.com:developersjp/podcast-freaks.git
  - npm run deploy
branches:
  - master